services:
 db:
  image: postgres:18
  container_name: postgres_db
  environment:
   POSTGRES_USER: snappit
   POSTGRES_PASSWORD: password
   POSTGRES_DB: snappit_db
  ports:
   - "5432:5432"
  volumes:
   - pgdata:/var/lib/postgresql

volumes:
 pgdata:
