[project]
name = "snappit-backend-py"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi",
  "sqlalchemy[asyncio]",
  "uvicorn",
  "alembic",
  "asyncpg",
  "pydantic-settings",
  "pydantic[email]",
  "psycopg[binary]",
  "httpx>=0.28.1",
  "paddle-python-sdk",
  "loguru"
]

[project.optional-dependencies]
dev = [
  "ruff",
  "basedpyright",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort
  "UP",  # pyupgrade
  "B",   # flake8-bugbear
]

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.basedpyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.12"
typeCheckingMode = "standard"
include = ["src"]
