"""Add license status fields

Revision ID: 3eb3e4b70560
Revises: 44d51e9d66ce
Create Date: 2026-05-14 13:47:57.708397

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3eb3e4b70560"
down_revision: Union[str, Sequence[str], None] = "44d51e9d66ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "paddle_webhook_events",
        sa.Column(
            "process_status",
            sa.Enum(
                "processed",
                "pending",
                "failed",
                "ignored",
                name="process_status",
                native_enum=False,
                length=20,
            ),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column(
        "paddle_webhook_events",
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "paddle_webhook_events",
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "paddle_webhook_events",
        sa.Column("last_error", sa.String(length=1000), nullable=True),
    )
    op.add_column(
        "paddle_webhook_events",
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.execute(
        "UPDATE paddle_webhook_events "
        "SET process_status = 'ignored', processed_at = now() "
        "WHERE process_status = 'pending'"
    )

    op.create_index(
        op.f("ix_paddle_webhook_events_next_attempt_at"),
        "paddle_webhook_events",
        ["next_attempt_at"],
        unique=False,
    )
    op.create_index(
        "ix_paddle_webhook_events_pending",
        "paddle_webhook_events",
        ["next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("process_status = 'pending'"),
    )
    op.create_index(
        op.f("ix_paddle_webhook_events_processed_at"),
        "paddle_webhook_events",
        ["processed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_paddle_webhook_events_processed_at"),
        table_name="paddle_webhook_events",
    )
    op.drop_index(
        "ix_paddle_webhook_events_pending",
        table_name="paddle_webhook_events",
        postgresql_where=sa.text("process_status = 'pending'"),
    )
    op.drop_index(
        op.f("ix_paddle_webhook_events_next_attempt_at"),
        table_name="paddle_webhook_events",
    )
    op.drop_column("paddle_webhook_events", "next_attempt_at")
    op.drop_column("paddle_webhook_events", "last_error")
    op.drop_column("paddle_webhook_events", "attempts")
    op.drop_column("paddle_webhook_events", "processed_at")
    op.drop_column("paddle_webhook_events", "process_status")
    # ### end Alembic commands ###
