"""Add licenses tables

Revision ID: 44d51e9d66ce
Revises: 2bbfc492fb11
Create Date: 2026-05-04 17:14:19.435575

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44d51e9d66ce"
down_revision: Union[str, Sequence[str], None] = "2bbfc492fb11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "licenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activation_code_hash", sa.String(length=64), nullable=False),
        sa.Column("activation_code_last4", sa.String(length=4), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("max_activations", sa.Integer(), server_default="2", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "revoked",
                "refunded",
                name="license_status",
                native_enum=False,
                length=20,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("paddle_event_id", sa.String(length=255), nullable=False),
        sa.Column("paddle_customer_id", sa.String(length=255), nullable=False),
        sa.Column("last_paddle_event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_activations > 0", name="ck_licenses_max_activations_positive"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activation_code_hash"),
    )
    op.create_index(op.f("ix_licenses_email"), "licenses", ["email"], unique=False)
    op.create_index(
        op.f("ix_licenses_paddle_customer_id"),
        "licenses",
        ["paddle_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_licenses_paddle_event_id"),
        "licenses",
        ["paddle_event_id"],
        unique=True,
    )
    op.create_index(op.f("ix_licenses_status"), "licenses", ["status"], unique=False)
    op.create_table(
        "license_activations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("license_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(length=255), nullable=False),
        sa.Column(
            "activated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["license_id"], ["licenses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_license_activations_device_id"),
        "license_activations",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_license_activations_license_id"),
        "license_activations",
        ["license_id"],
        unique=False,
    )
    op.create_index(
        "uq_license_activations_active_device",
        "license_activations",
        ["license_id", "device_id"],
        unique=True,
        postgresql_where="deactivated_at IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_license_activations_active_device",
        table_name="license_activations",
        postgresql_where="deactivated_at IS NULL",
    )
    op.drop_index(
        op.f("ix_license_activations_license_id"), table_name="license_activations"
    )
    op.drop_index(
        op.f("ix_license_activations_device_id"), table_name="license_activations"
    )
    op.drop_table("license_activations")
    op.drop_index(op.f("ix_licenses_status"), table_name="licenses")
    op.drop_index(op.f("ix_licenses_paddle_event_id"), table_name="licenses")
    op.drop_index(op.f("ix_licenses_paddle_customer_id"), table_name="licenses")
    op.drop_index(op.f("ix_licenses_email"), table_name="licenses")
    op.drop_table("licenses")
    # ### end Alembic commands ###
